### ISSUE TITLE
Dataset having no depth infomation?

### ISSUE THREAD

**Issue by AaronChuh** [NVlabs/mimicgen_environments#10]
Hi, I really apprecitate your work, and plan to train my model on your dataset. 
However, checking the dataset infomation with script `get_dataset_info.py` provided by robomimic, I find your dataset doesn't have depth infomation in it. How can I generate data that contain depth info? Could you provide something like the raw file in robomimic so that I can generate specific dataset I need? 
Look forward to reply,  thanks!

**Comment by amandlek** [comment]
You should be able to extract depth observations using these hdf5s (they are equivalent to the raw hdf5s from robomimic) with a command like [this one](https://github.com/ARISE-Initiative/robomimic/blob/b4f2d173f8161a1bedf13b5f045f05b4d6d38d9e/robomimic/scripts/dataset_states_to_obs.py#L37)

**Comment by Zhangwenyao1** [comment]
Thanks for your great work！
Are there any segmentation mask in the dataset？
