### ISSUE TITLE
how to generate data of core/object

### ISSUE THREAD

**Issue by GreenAvocado92** [NVlabs/mimicgen_environments#5]
Hi,
   I can execute the code according to the readme, but I don’t know how to generate data from source. Do you mind providing an introduction manual?

**Comment by amandlek** [comment]
The generation code has not been released yet (see [this](https://github.com/NVlabs/mimicgen_environments#data-generation-code)).

**Comment by GreenAvocado92** [comment]
Hi，if I have a robot,  would you mind tell me how to generate a dataset?

**Comment by amandlek** [comment]
As I mentioned earlier, the generation code has not been released yet (see [this](https://github.com/NVlabs/mimicgen_environments#data-generation-code)).
